CREATE TABLE SPRINT (
    SPRINT_ID UUID PRIMARY KEY,
    PROJECT_ID UUID NOT NULL,
    SPRINT_NAME VARCHAR(200) NOT NULL,
    GOAL TEXT,
    STATUS VARCHAR(30) NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP,
    CONSTRAINT FK_SPRINT_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT (PROJECT_ID),
    CONSTRAINT CK_SPRINT_STATUS CHECK (STATUS IN ('PLANNED', 'ACTIVE', 'CLOSED')),
    CONSTRAINT CK_SPRINT_DATE CHECK (END_DATE >= START_DATE)
);

CREATE INDEX IDX_SPRINT_PROJECT_ID ON SPRINT (PROJECT_ID);
CREATE INDEX IDX_SPRINT_PROJECT_STATUS ON SPRINT (PROJECT_ID, STATUS);
CREATE INDEX IDX_SPRINT_DATE ON SPRINT (START_DATE, END_DATE);

CREATE TABLE SPRINT_ISSUE (
    SPRINT_ID UUID NOT NULL,
    ISSUE_ID UUID NOT NULL,
    DISPLAY_ORDER INTEGER NOT NULL DEFAULT 0,
    CREATED_AT TIMESTAMP NOT NULL,
    PRIMARY KEY (SPRINT_ID, ISSUE_ID),
    CONSTRAINT FK_SPRINT_ISSUE_SPRINT FOREIGN KEY (SPRINT_ID) REFERENCES SPRINT (SPRINT_ID) ON DELETE CASCADE,
    CONSTRAINT FK_SPRINT_ISSUE_ISSUE FOREIGN KEY (ISSUE_ID) REFERENCES ISSUE (ISSUE_ID),
    CONSTRAINT CK_SPRINT_ISSUE_DISPLAY_ORDER CHECK (DISPLAY_ORDER >= 0)
);

CREATE INDEX IDX_SPRINT_ISSUE_ISSUE_ID ON SPRINT_ISSUE (ISSUE_ID);
CREATE INDEX IDX_SPRINT_ISSUE_ORDER ON SPRINT_ISSUE (SPRINT_ID, DISPLAY_ORDER);
