CREATE TABLE SPRINT_DAILY_SNAPSHOT (
    SNAPSHOT_ID UUID PRIMARY KEY,
    SPRINT_ID UUID NOT NULL,
    SNAPSHOT_DATE DATE NOT NULL,
    TOTAL_ISSUE_COUNT INTEGER NOT NULL,
    DONE_ISSUE_COUNT INTEGER NOT NULL,
    REMAINING_ISSUE_COUNT INTEGER NOT NULL,
    TOTAL_ESTIMATED_MINUTES INTEGER NOT NULL,
    DONE_ESTIMATED_MINUTES INTEGER NOT NULL,
    REMAINING_ESTIMATED_MINUTES INTEGER NOT NULL,
    SPENT_MINUTES INTEGER NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT FK_SPRINT_DAILY_SNAPSHOT_SPRINT FOREIGN KEY (SPRINT_ID) REFERENCES SPRINT (SPRINT_ID) ON DELETE CASCADE,
    CONSTRAINT UQ_SPRINT_DAILY_SNAPSHOT_DATE UNIQUE (SPRINT_ID, SNAPSHOT_DATE),
    CONSTRAINT CK_SPRINT_DAILY_SNAPSHOT_COUNTS CHECK (
        TOTAL_ISSUE_COUNT >= 0
        AND DONE_ISSUE_COUNT >= 0
        AND REMAINING_ISSUE_COUNT >= 0
    ),
    CONSTRAINT CK_SPRINT_DAILY_SNAPSHOT_MINUTES CHECK (
        TOTAL_ESTIMATED_MINUTES >= 0
        AND DONE_ESTIMATED_MINUTES >= 0
        AND REMAINING_ESTIMATED_MINUTES >= 0
        AND SPENT_MINUTES >= 0
    )
);
