CREATE TABLE PROJECT (
    PROJECT_ID UUID PRIMARY KEY,
    PROJECT_CODE VARCHAR(50) NOT NULL UNIQUE,
    PROJECT_NAME VARCHAR(200) NOT NULL,
    CLIENT_NAME VARCHAR(200),
    DESCRIPTION TEXT,
    START_DATE DATE,
    END_DATE DATE,
    STATUS VARCHAR(30) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP
);
