CREATE TABLE ISSUE (
    ISSUE_ID UUID PRIMARY KEY,
    PROJECT_ID UUID NOT NULL,
    ISSUE_KEY VARCHAR(50) NOT NULL UNIQUE,
    ISSUE_TYPE VARCHAR(30) NOT NULL,
    TITLE VARCHAR(500) NOT NULL,
    DESCRIPTION TEXT,
    STATUS VARCHAR(30) NOT NULL,
    PRIORITY VARCHAR(30) NOT NULL,
    ASSIGNEE_ID UUID,
    REPORTER_ID UUID,
    START_DATE DATE,
    DUE_DATE DATE,
    RESOLVED_DATE DATE,
    ESTIMATED_MINUTES INTEGER DEFAULT 0,
    SPENT_MINUTES INTEGER DEFAULT 0,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP,
    CONSTRAINT FK_ISSUE_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT (PROJECT_ID)
);

CREATE INDEX IDX_ISSUE_PROJECT_ID ON ISSUE (PROJECT_ID);
CREATE INDEX IDX_ISSUE_STATUS ON ISSUE (STATUS);
CREATE INDEX IDX_ISSUE_PROJECT_STATUS ON ISSUE (PROJECT_ID, STATUS);
