CREATE TABLE APP_USER (
    USER_ID UUID PRIMARY KEY,
    USERNAME VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD_HASH TEXT NOT NULL,
    DISPLAY_NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(200),
    ROLE VARCHAR(30) NOT NULL,
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP
);

INSERT INTO APP_USER (
    USER_ID,
    USERNAME,
    PASSWORD_HASH,
    DISPLAY_NAME,
    EMAIL,
    ROLE,
    IS_ACTIVE,
    CREATED_AT,
    UPDATED_AT
) VALUES (
    '00000000-0000-0000-0000-000000000001',
    'admin',
    '$2a$10$9avVY6XbhwMXP4nN8pDizuCwYKU6FvJm29E47jW6MRP2PIdO6cyoC',
    '관리자',
    NULL,
    'ADMIN',
    TRUE,
    CURRENT_TIMESTAMP,
    NULL
);
