CREATE TABLE WORK_LOG (
    WORK_LOG_ID UUID PRIMARY KEY,
    ISSUE_ID UUID NOT NULL,
    USER_ID UUID NOT NULL,
    WORK_DATE DATE NOT NULL,
    WORK_CONTENT TEXT NOT NULL,
    SPENT_MINUTES INTEGER NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT FK_WORK_LOG_ISSUE FOREIGN KEY (ISSUE_ID) REFERENCES ISSUE (ISSUE_ID),
    CONSTRAINT FK_WORK_LOG_USER FOREIGN KEY (USER_ID) REFERENCES APP_USER (USER_ID),
    CONSTRAINT CK_WORK_LOG_SPENT_MINUTES CHECK (SPENT_MINUTES >= 0)
);

CREATE INDEX IDX_WORK_LOG_ISSUE_ID ON WORK_LOG (ISSUE_ID);
CREATE INDEX IDX_WORK_LOG_USER_ID ON WORK_LOG (USER_ID);
CREATE INDEX IDX_WORK_LOG_WORK_DATE ON WORK_LOG (WORK_DATE);
