CREATE TABLE COLUMN_SPEC (
    COLUMN_SPEC_ID UUID PRIMARY KEY,
    PROJECT_ID UUID NOT NULL,
    TABLE_NAME VARCHAR(100) NOT NULL,
    TABLE_COMMENT VARCHAR(500),
    COLUMN_NAME VARCHAR(100) NOT NULL,
    COLUMN_COMMENT VARCHAR(500),
    DATA_TYPE VARCHAR(100),
    DATA_LENGTH VARCHAR(50),
    IS_NULLABLE VARCHAR(1),
    IS_PK VARCHAR(1),
    IS_FK VARCHAR(1),
    DEFAULT_VALUE VARCHAR(500),
    REMARK TEXT,
    CREATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT FK_COLUMN_SPEC_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT (PROJECT_ID)
);

CREATE INDEX IDX_COLUMN_SPEC_PROJECT_ID ON COLUMN_SPEC (PROJECT_ID);
CREATE INDEX IDX_COLUMN_SPEC_TABLE_NAME ON COLUMN_SPEC (TABLE_NAME);
