CREATE TABLE VCS_CHANGE_LOG (
    CHANGE_LOG_ID UUID PRIMARY KEY,
    PROJECT_ID UUID NOT NULL,
    VCS_TYPE VARCHAR(20) NOT NULL,
    REVISION_NO VARCHAR(100) NOT NULL,
    AUTHOR VARCHAR(100),
    CHANGED_AT TIMESTAMP,
    MESSAGE TEXT,
    CREATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT FK_VCS_CHANGE_LOG_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT (PROJECT_ID)
);

CREATE TABLE VCS_CHANGE_FILE (
    CHANGE_FILE_ID UUID PRIMARY KEY,
    CHANGE_LOG_ID UUID NOT NULL,
    FILE_PATH VARCHAR(1000) NOT NULL,
    CHANGE_TYPE VARCHAR(30),
    CONSTRAINT FK_VCS_CHANGE_FILE_LOG FOREIGN KEY (CHANGE_LOG_ID) REFERENCES VCS_CHANGE_LOG (CHANGE_LOG_ID)
);

CREATE TABLE ISSUE_CHANGE_LOG_MAP (
    ISSUE_ID UUID NOT NULL,
    CHANGE_LOG_ID UUID NOT NULL,
    PRIMARY KEY (ISSUE_ID, CHANGE_LOG_ID),
    CONSTRAINT FK_ISSUE_CHANGE_LOG_MAP_ISSUE FOREIGN KEY (ISSUE_ID) REFERENCES ISSUE (ISSUE_ID),
    CONSTRAINT FK_ISSUE_CHANGE_LOG_MAP_LOG FOREIGN KEY (CHANGE_LOG_ID) REFERENCES VCS_CHANGE_LOG (CHANGE_LOG_ID)
);

CREATE INDEX IDX_VCS_CHANGE_LOG_PROJECT_ID ON VCS_CHANGE_LOG (PROJECT_ID);
CREATE INDEX IDX_VCS_CHANGE_LOG_VCS_TYPE ON VCS_CHANGE_LOG (VCS_TYPE);
CREATE INDEX IDX_VCS_CHANGE_FILE_LOG_ID ON VCS_CHANGE_FILE (CHANGE_LOG_ID);
CREATE INDEX IDX_ISSUE_CHANGE_LOG_MAP_LOG_ID ON ISSUE_CHANGE_LOG_MAP (CHANGE_LOG_ID);
