CREATE TABLE ARTIFACT_HISTORY (
    ARTIFACT_ID UUID PRIMARY KEY,
    PROJECT_ID UUID NOT NULL,
    ARTIFACT_TYPE VARCHAR(50) NOT NULL,
    FILE_NAME VARCHAR(300) NOT NULL,
    FILE_PATH VARCHAR(1000),
    GENERATED_BY UUID,
    GENERATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT FK_ARTIFACT_HISTORY_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT (PROJECT_ID),
    CONSTRAINT FK_ARTIFACT_HISTORY_USER FOREIGN KEY (GENERATED_BY) REFERENCES APP_USER (USER_ID)
);

CREATE INDEX IDX_ARTIFACT_HISTORY_PROJECT_ID ON ARTIFACT_HISTORY (PROJECT_ID);
CREATE INDEX IDX_ARTIFACT_HISTORY_TYPE ON ARTIFACT_HISTORY (ARTIFACT_TYPE);
CREATE INDEX IDX_ARTIFACT_HISTORY_GENERATED_AT ON ARTIFACT_HISTORY (GENERATED_AT);
