CREATE TABLE TEST_EVIDENCE (
    TEST_EVIDENCE_ID UUID PRIMARY KEY,
    PROJECT_ID UUID NOT NULL,
    ISSUE_ID UUID NOT NULL,
    TEST_NAME VARCHAR(300) NOT NULL,
    TEST_TARGET VARCHAR(500) NOT NULL,
    TEST_PROCEDURE TEXT NOT NULL,
    EXPECTED_RESULT TEXT NOT NULL,
    ACTUAL_RESULT TEXT NOT NULL,
    RESULT_STATUS VARCHAR(30) NOT NULL,
    TESTER_ID UUID NOT NULL,
    TESTED_AT TIMESTAMP NOT NULL,
    SCREENSHOT_FILE_NAME VARCHAR(300),
    SCREENSHOT_FILE_PATH VARCHAR(1000),
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP,
    CONSTRAINT FK_TEST_EVIDENCE_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT (PROJECT_ID),
    CONSTRAINT FK_TEST_EVIDENCE_ISSUE FOREIGN KEY (ISSUE_ID) REFERENCES ISSUE (ISSUE_ID),
    CONSTRAINT FK_TEST_EVIDENCE_TESTER FOREIGN KEY (TESTER_ID) REFERENCES APP_USER (USER_ID),
    CONSTRAINT CK_TEST_EVIDENCE_RESULT_STATUS CHECK (RESULT_STATUS IN ('SUCCESS', 'FAIL', 'BLOCKED'))
);

CREATE INDEX IDX_TEST_EVIDENCE_PROJECT_ID ON TEST_EVIDENCE (PROJECT_ID);
CREATE INDEX IDX_TEST_EVIDENCE_ISSUE_ID ON TEST_EVIDENCE (ISSUE_ID);
CREATE INDEX IDX_TEST_EVIDENCE_RESULT_STATUS ON TEST_EVIDENCE (RESULT_STATUS);
CREATE INDEX IDX_TEST_EVIDENCE_TESTED_AT ON TEST_EVIDENCE (TESTED_AT);
