CREATE TABLE WBS_TASK (
    WBS_TASK_ID UUID PRIMARY KEY,
    PROJECT_ID UUID NOT NULL,
    PARENT_TASK_ID UUID,
    ISSUE_ID UUID,
    WBS_CODE VARCHAR(50) NOT NULL,
    TASK_NAME VARCHAR(300) NOT NULL,
    TASK_DESCRIPTION TEXT,
    TASK_TYPE VARCHAR(30) NOT NULL,
    STATUS VARCHAR(30) NOT NULL,
    ASSIGNEE_ID UUID,
    PLAN_START_DATE DATE NOT NULL,
    PLAN_END_DATE DATE NOT NULL,
    ACTUAL_START_DATE DATE,
    ACTUAL_END_DATE DATE,
    ESTIMATED_MINUTES INTEGER NOT NULL DEFAULT 0,
    SPENT_MINUTES INTEGER NOT NULL DEFAULT 0,
    PROGRESS_RATE INTEGER NOT NULL DEFAULT 0,
    DISPLAY_ORDER INTEGER NOT NULL DEFAULT 0,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP,
    CONSTRAINT FK_WBS_TASK_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT (PROJECT_ID),
    CONSTRAINT FK_WBS_TASK_PARENT FOREIGN KEY (PARENT_TASK_ID) REFERENCES WBS_TASK (WBS_TASK_ID),
    CONSTRAINT FK_WBS_TASK_ISSUE FOREIGN KEY (ISSUE_ID) REFERENCES ISSUE (ISSUE_ID),
    CONSTRAINT FK_WBS_TASK_ASSIGNEE FOREIGN KEY (ASSIGNEE_ID) REFERENCES APP_USER (USER_ID),
    CONSTRAINT UQ_WBS_TASK_PROJECT_CODE UNIQUE (PROJECT_ID, WBS_CODE),
    CONSTRAINT CK_WBS_TASK_TYPE CHECK (TASK_TYPE IN ('PHASE', 'DELIVERABLE', 'TASK')),
    CONSTRAINT CK_WBS_TASK_STATUS CHECK (STATUS IN ('READY', 'IN_PROGRESS', 'DONE', 'HOLD')),
    CONSTRAINT CK_WBS_TASK_PLAN_DATE CHECK (PLAN_END_DATE >= PLAN_START_DATE),
    CONSTRAINT CK_WBS_TASK_MINUTES CHECK (ESTIMATED_MINUTES >= 0 AND SPENT_MINUTES >= 0),
    CONSTRAINT CK_WBS_TASK_PROGRESS CHECK (PROGRESS_RATE BETWEEN 0 AND 100)
);

CREATE INDEX IDX_WBS_TASK_PROJECT_ID ON WBS_TASK (PROJECT_ID);
CREATE INDEX IDX_WBS_TASK_PARENT_TASK_ID ON WBS_TASK (PARENT_TASK_ID);
CREATE INDEX IDX_WBS_TASK_ISSUE_ID ON WBS_TASK (ISSUE_ID);
CREATE INDEX IDX_WBS_TASK_PLAN_DATE ON WBS_TASK (PLAN_START_DATE, PLAN_END_DATE);

CREATE TABLE WBS_TASK_DEPENDENCY (
    DEPENDENCY_ID UUID PRIMARY KEY,
    PROJECT_ID UUID NOT NULL,
    PREDECESSOR_TASK_ID UUID NOT NULL,
    SUCCESSOR_TASK_ID UUID NOT NULL,
    DEPENDENCY_TYPE VARCHAR(30) NOT NULL,
    LAG_DAYS INTEGER NOT NULL DEFAULT 0,
    CREATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT FK_WBS_DEPENDENCY_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT (PROJECT_ID),
    CONSTRAINT FK_WBS_DEPENDENCY_PREDECESSOR FOREIGN KEY (PREDECESSOR_TASK_ID) REFERENCES WBS_TASK (WBS_TASK_ID),
    CONSTRAINT FK_WBS_DEPENDENCY_SUCCESSOR FOREIGN KEY (SUCCESSOR_TASK_ID) REFERENCES WBS_TASK (WBS_TASK_ID),
    CONSTRAINT UQ_WBS_DEPENDENCY_PAIR UNIQUE (PREDECESSOR_TASK_ID, SUCCESSOR_TASK_ID, DEPENDENCY_TYPE),
    CONSTRAINT CK_WBS_DEPENDENCY_TYPE CHECK (DEPENDENCY_TYPE IN ('FINISH_TO_START')),
    CONSTRAINT CK_WBS_DEPENDENCY_SELF CHECK (PREDECESSOR_TASK_ID <> SUCCESSOR_TASK_ID)
);

CREATE INDEX IDX_WBS_DEPENDENCY_PROJECT_ID ON WBS_TASK_DEPENDENCY (PROJECT_ID);
CREATE INDEX IDX_WBS_DEPENDENCY_PREDECESSOR ON WBS_TASK_DEPENDENCY (PREDECESSOR_TASK_ID);
CREATE INDEX IDX_WBS_DEPENDENCY_SUCCESSOR ON WBS_TASK_DEPENDENCY (SUCCESSOR_TASK_ID);
